// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> en = {
  "profile": "Profile",
  "sign_in": "Sign In",
  "sign_up": "Sign Up",
  "sign_out": "Sign Out",
  "home": "Home",
  "markers": "Marker",
  "forgot_password": "Forgot Password",
  "edit_profile": "Edit Profile",
  "enter_your_email": "Enter Your Email",
  "enter_your_password": "Enter Your Password",
  "enter_your_name": "Enter Your Name",
  "enter_new_password": "Enter Your New Password",
  "confirm_password": "Confirm Your Password",
  "do_not_have_an_account": "Don't have an account?",
  "already_have_an_account": "Already have an account?",
  "email_is_required": "Email is required",
  "password_is_required": "Password is required",
  "name_is_required": "Name is required",
  "confirm_password_is_required": "Confirm password is required",
  "password_does_not_match": "Password does not match",
  "enter_valid_email": "Please enter a valid email!",
  "reset_password_link_sent": "A reset password link sent to your email",
  "send_me_reset_password_link": "Send me reset password link",
  "sign_in_successfully": "Sign in successfully",
  "sign_up_successfully": "Sign up successfully",
  "check_credential_again": "Please check your credential again!",
  "email_already_in_use": "Email already in use!",
  "use_another_email": "Please use another email",
  "enter_stronger_password": "Please enter a stronger password",
  "guess": "guess",
  "greeting": "Hey {},",
  "our_pet": "Our Pet",
  "pet_accessories": "Pet Accessories",
  "pet_food": "Pet Food",
  "there_is_no_data": "There is no data here",
  "add_item_to_cart_successfully": "Add Item To Cart Successfully",
  "order_successfully": "Your Order Complete Successfully",
  "something_went_wrong": "Some thing went wrong, try again later!",
  "quantity": "Quantity: ",
  "add_to_cart": "Add to Cart",
  "your_cart": "Your Cart",
  "view_detail": "View Detail",
  "hide_detail": "Hide Detail",
  "check_out": "Check Out {}",
  "brand": "Brand: {}",
  "leave_us_message": "Leave Us Your Message",
  "sub_total": "SubTotal",
  "shipping_charges": "Shipping Charges",
  "total": "Total",
  "there_is_nothing_here": "There is nothing here. Let's add an item ",
  "delete": "Delete",
  "hide": "Hide",
  "loading": "Loading ...",
  "you_can_only_add_one": "You can only add once with pet!",
  "explore": "Explore",
  "sign_in_to_shopping": "Sign in to continue?",
  "need_to_sign_in_description": "You need to sign in to add something to cart, go to sign in?",
  "cancel": "Cancel",
  "get_with": "Get {} with {} now",
  "pet_profile": "{}'s profile",
  "about_pet": "About {}",
  "pet_status": "{}'s Status",
  "gender": "Gender:",
  "male": "Male",
  "female": "Female",
  "weight": "Weight:",
  "height": "Height:",
  "color": "Color:",
  "birthday": "Birthday:",
  "explore_now": "Explore Now",
  "about_to_sign_out": "About to sign out?",
  "are_you_sure_to_sign_out": "Are you sure about to Sign Out?",
  "about_to_delete": "About to delete?",
  "are_you_sure_to_delete": "Are you sure about to delete this item from cart?",
  "share": "Share",
  "let_check_this_product": "Let's check this product: {}",
  "let_check_this_cute_pet": "Let's check this cute pet: {}",
  "explore_more_fantastic_products": "Explore more fantastic products: {}",
  "address": "Address: ",
  "phone_number": "Phone Number {}:",
  "marker_information": "Marker Information",
  "description": "Description:",
  "work_time": "Work Time: {} - {}",
  "let_check_this_store": "Let check this store: {}",
  "all_markers": "All Markers"
};
static const Map<String,dynamic> vi_VI = {
  "profile": "Hồ sơ",
  "sign_in": "Đăng Nhập",
  "sign_up": "Đăng Ký",
  "sign_out": "Đăng Xuất",
  "home": "Trang chủ",
  "markers": "Cửa hàng",
  "forgot_password": "Quên Mật Khẩu",
  "enter_your_email": "Địa chỉ email của bạn",
  "enter_your_password": "Nhập mật khẩu của bạn",
  "enter_your_name": "Tên của bạn",
  "enter_new_password": "Nhập mật khẩu mới",
  "confirm_password": "Nhập lại mật khẩu",
  "do_not_have_an_account": "Bạn chưa có tài khoản?",
  "already_have_an_account": "Bạn đã có tài khoản?",
  "email_is_required": "Email không thể để trống",
  "password_is_required": "Mật khẩu không thể để trống",
  "name_is_required": "Tên không thể để trống",
  "confirm_password_is_required": "Nhập lại mật khẩu không thể để trống",
  "password_does_not_match": "Mật khẩu không khớp",
  "enter_valid_email": "Vui lòng nhập một email hợp lệ!",
  "reset_password_link_sent": "Đường dẫn cập nhật mật khẩu đã được gửi tới email của bạn!",
  "send_me_reset_password_link": "Lấy mật khẩu",
  "sign_in_successfully": "Đăng nhập thành công",
  "sign_up_successfully": "Đăng ký thành công",
  "check_credential_again": "Vui lòng kiểm tra lại thông tin đăng nhập!",
  "email_already_in_use": "Email này đã đăng kí!",
  "use_another_email": "Vui lòng sử dụng email khác!",
  "enter_stronger_password": "Vui lòng nhập một mật khẩu mạnh hơn!",
  "edit_profile": "Chỉnh sửa hồ sơ",
  "guess": "khách",
  "greeting": "Chào {},",
  "our_pet": "Thú cưng",
  "pet_accessories": "Phụ kiện",
  "pet_food": "Thức ăn",
  "there_is_no_data": "Không có dữ liệu",
  "add_item_to_cart_successfully": "Thêm sản phẩm vào giỏ hàng thành công",
  "order_successfully": "Đặt hàng thành công",
  "something_went_wrong": "Có lỗi xảy ra, vui lòng thử lại sau!",
  "quantity": "Số lượng: ",
  "add_to_cart": "Thêm vào giỏ hàng",
  "your_cart": "Giỏ hàng của bạn",
  "view_detail": "Xem chi tiết",
  "hide_detail": "Ẩn chi tiết",
  "check_out": "Thanh toán {}",
  "brand": "NSX: {}",
  "leave_us_message": "Lời nhắn cho đơn hàng",
  "sub_total": "Tổng tiền",
  "shipping_charges": "Phí vận chuyển",
  "total": "Tổng cộng",
  "there_is_nothing_here": "Không có gì ở đây, mua sắm ngay!",
  "delete": "Xóa",
  "hide": "Ẩn",
  "loading": "Đang tải ...",
  "you_can_only_add_one": "Thú cưng chỉ được thêm vào giỏ hàng 1 lần!",
  "explore": "Khám phá",
  "sign_in_to_shopping": "Đăng nhập để tiếp tục?",
  "need_to_sign_in_description": "Bạn cần đăng nhập để thêm hàng vào giỏ, đến trang đăng nhập?",
  "cancel": "Hủy",
  "get_with": "Chọn {} với {} ngay",
  "pet_profile": "Hồ sơ của {}",
  "about_pet": "Giới thiệu về {}",
  "pet_status": "Thông tin của {}",
  "gender": "Giới tính:",
  "male": "Giống Đực",
  "female": "Giống Cái",
  "weight": "Cân nặng:",
  "height": "Chiều cao:",
  "color": "Màu sắc:",
  "birthday": "Ngày sinh:",
  "explore_now": "Khám phá ngay",
  "about_to_sign_out": "Bạn muốn đăng xuất?",
  "are_you_sure_to_sign_out": "Bạn có chắc muốn đăng xuất không?",
  "about_to_delete": "Xóa món hàng?",
  "are_you_sure_to_delete": "Bạn có chắc muốn xóa món hàng khỏi giỏ không?",
  "share": "Chia sẻ",
  "let_check_this_product": "Xem ngay sản phẩm yêu thích của tôi: {}",
  "let_check_this_cute_pet": "Xem ngay bé thú cưng đáng yêu này nè: {}",
  "explore_more_fantastic_products": "Khám phá những sản phẩm tuyệt vời ngay: {}",
  "address": "Địa chỉ: ",
  "phone_number": "SĐT: {}",
  "marker_information": "Thông tin cửa hàng",
  "description": "Giới thiệu về cửa hàng:",
  "work_time": "Thời gian làm việc: {} - {}",
  "let_check_this_store": "Xem ngay shop xịn nè: {}",
  "all_markers": "Các cửa hàng của chúng tôi"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": en, "vi_VI": vi_VI};
}
